포켓몬 모델 작성
WeOrder-Dev-Wopark/poke-flutter pull request #1
Opened 2024-05-28 08:06 UTC by WeOrder-Dev-Wopark

포켓몬 모델에 필요한 초기 모델 작성
Pokemon
- PokemonType
- Stat

2024-05-28 08:17 UTC, woogi-kang commented
PokemonType Enum으로 재정의 필요

1. id
2. name
3. color
4. icon (Asset 처리)

Enum 처리로 진행. Dart 3.0 이후 Document 참고.
Extension 방식으로 json parsing 하도록 참고.  (dynamic Data to Enum).

2024-05-28 08:32 UTC, woogi-kang requested changes
PokemonType Enum으로 재정의 필요
- id
- name
- color
- icon (Asset 처리)
Enum 처리로 진행. Dart 3.0 이후 Document 참고.
Extension 방식으로 json parsing 하도록 참고. (dynamic Data to Enum).

----------------------
모델 미비된 부분 마무리 
- 설명
- Moves
- 포켓몬 이미지
- type 이미지

2024-05-29 06:15 UTC, WeOrder-Dev-Wopark commented
> PokemonType Enum으로 재정의 필요
> 
> * id
> * name
> * color
> * icon (Asset 처리)
>   Enum 처리로 진행. Dart 3.0 이후 Document 참고.
>   Extension 방식으로 json parsing 하도록 참고. (dynamic Data to Enum).
> 
> 모델 미비된 부분 마무리
> 
> * 설명
> * Moves
> * 포켓몬 이미지
> * type 이미지

포켓몬 설명이 없어요 ㅠ

2024-05-29 07:39 UTC, woogi-kang approved these changes

2024-05-29 07:39 UTC, merged